#
#
#
#
#
#
enabled: true # Включить / выключить ограничение предметов.

message_interval: 2500 # Интервал в миллисекундах между сообщениями о лимите предмета.
check_inventory_interval: 30 # Интервал проверки инвентарей в тиках. 1 секунда = 20 тиков. Рекомендуется устанавливать не менее 20.

disabled_worlds:
  - "example_world"

restricts:
  #example_stone:
  #  material:
  #    - "stone"
  #    - "cobblestone"
  #  enchantments: # [], чтобы отключить.
  #    - "sharpness;5"
  #    - "thorns;3"
  #  potion_type: # [], чтобы отключить.
  #    - "healing"
  #    - "strong_healing"
  #  custom_model_data: 666 # -1, чтобы отключить.
  #  max_amount: 3 # Максимальное кол-во предмета
  #  message: "&8[&#ff3030&l!&8] &7Вы не можете иметь более &6%amount% крутых камней в инвентаре!;action_bar" # "<сообщение>;<тип вывода>". chat, action_bar

  example:
    material:
      - "experience_bottle"
    enchantments: []
    potion_type: []
    custom_model_data: -1
    max_amount: 16
    message: "&8[&#ff3030&l!&8] &7Вы не можете иметь более &6%amount% пузырьков опыта в инвентаре!;chat"

messages:
  reload: "&7ItemRestrictor перезагружен."
  usage: "&7Использование: /itemrestrictor reload."
  no_permission: "&#ff4040У вас нет прав для выполнения этой команды."